using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Restaurant.Models
{
    public class RestaurantData : DropCreateDatabaseAlways<RestEntities>
    {
        protected override void Seed(RestEntities context)
        {
            var restMenus = new List<RestMenu>
            {
                new RestMenu { Name = "NIBBLES AND ANTIPASTI" },
                new RestMenu { Name = "PASTA" },
                new RestMenu { Name = "RAVIOLI" },
                new RestMenu { Name = "MAINS & SIDES" },
                new RestMenu { Name = "DESSERTS" },
                new RestMenu { Name = "KIDS MENU" },
                new RestMenu { Name = "KIDS DESSERTS" },
                new RestMenu { Name = "APRERITIVO" }, 
                new RestMenu { Name = "BEER" },
                new RestMenu { Name = "NON-ALCOHOLIC COCKTAILS" },
                new RestMenu { Name = "COCKTAILS" },
                new RestMenu { Name = "WHITE WINE" },
                new RestMenu { Name = "RED WINE" },
                new RestMenu { Name = "ROSE WINE" },
                new RestMenu { Name = "SPARKLING" },
                new RestMenu { Name = "JAMIE'S ITALIAN HOUSE WINE" },
                new RestMenu { Name = "SOFT DRINKS" },
                new RestMenu { Name = "DESSERT COCKTAILS" },
                new RestMenu { Name = "HOT DRINKS" },
                new RestMenu { Name = "DIGESTIFS" },

            };

            restMenus.ForEach(s => context.RestMenus.Add(s));
            context.SaveChanges();            

            new List<RestItem>
            {
                new RestItem { Title = "TOMATO & RICOTTA BRUSCHETTA", RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"), Price = 4.95M,   RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ULTIMATE GARLIC BREAD", RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"), Price = 3.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FREE-RANGE PORK SCRATCHINGS", RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ARTISAN BREAD BASKET", RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"), Price = 10.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "PATE BRUSCHETTA", RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CRISPY SQUID", RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"), Price = 14.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem{Title="MUSHROOM FRITTI", RestMenu=restMenus.Single(g=>g.Name=="NIBBLES AND ANTIPASTI"),Price = 5.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="ITALIAN NACHOS",RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 4.25M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="CORNISH CRAB BRUSCHETTA",RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 6.70M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="WORLD’S BEST OLIVES ON ICE",RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 3.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="PRIMAVERA BRUSCHETTA",RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 4.95M, RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="PEA & MINT ARANCINI",RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 5.25M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="VEGETABLE PLANK",RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="ULTIMATE PLANK", RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 10.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem{Title="CURED MEAT PLANK",RestMenu = restMenus.Single(g => g.Name == "NIBBLES AND ANTIPASTI"),Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif"},
                new RestItem { Title = "OUR FAMOUS PRAWN LINGUINE", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 14.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TAGLIATELLE BOLOGNESE", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 10.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TURBO RIGATONI ARRABBIATA", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 9.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BAKED CRESPELLE", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 11.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SPICY SAUSAGE CASARECCE", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 11.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "VEGGIE TAGLIATELLE BOLOGNESE", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 9.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SPAGHETTI CARBONARA", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 10.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SQUID & MUSSEL SPAGHETTI NERO", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 12.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FRESH CRAB SPAGHETTI", RestMenu = restMenus.Single(g => g.Name == "PASTA"), Price = 13.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "RAVIOLI GENOVESE", RestMenu = restMenus.Single(g => g.Name == "RAVIOLI"), Price = 11.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TORTELLINI CON CARNE", RestMenu = restMenus.Single(g => g.Name == "RAVIOLI"), Price = 12.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MEZZALUNA CAPRESE", RestMenu = restMenus.Single(g => g.Name == "RAVIOLI"), Price = 11.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TURKEY MILANESE", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 13.75M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ITALIAN STEAK & FRIES", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 15.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE’S FAVOURITE PORCHETTA", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 13.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GENNARO’S CHICKEN PRIMAVERA", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 13.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "HERBY LAMB STEAK", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 16.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE’S ITALIAN BURGER", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 10.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "VEGGIE BURGER", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 10.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "35-DAY DRY-AGED SIRLOIN STEAK", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 22.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SICILIAN-SPICED AUBERGINE", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 9.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JI SUPER FOOD SALAD", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 9.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CAESAR SALAD", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 9.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "HERITAGE TOMATO SALAD", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 9.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FUNKY CHIPS", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.85M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CAPRESE SALAD", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BUTTERY POTATOES & GREEN BEANS", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "POLENTA CHIPS", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.65M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SEASONAL GREENS", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SPICED FRIES", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.85M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ROCKET & PARMESAN SALAD", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MARKET SALAD", RestMenu = restMenus.Single(g => g.Name == "MAINS & SIDES"), Price = 3.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ORGANIC YOGHURT PANNA COTTA", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 5.55M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "VIN SANTO TIRAMISU", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 5.55M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MOLTEN CHOCOLATE PRALINE PUDDING", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 6.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BAKED WHITE CHOCOLATE CHEESECAKE", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 5.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE’S FAVOURITE ORANGE BLOSSOM POLENTA CAKE", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 5.55M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "EPIC BROWNIE", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 5.75M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "STRAWBERRIES & FROZEN YOGHURT", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 5.55M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ORGANIC ICE CREAM", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 4.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SORBET", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 4.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "YOGHURT", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 4.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TOPPINGS", RestMenu = restMenus.Single(g => g.Name == "DESSERTS"), Price = 4.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE'S PROPER PICNIC BOX", RestMenu = restMenus.Single(g => g.Name == "KIDS MENU"), Price = 6.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ORGANIC SALMON IN A BAG", RestMenu = restMenus.Single(g => g.Name == "KIDS MENU"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ORGANIC MINI SPAGHETTI & MEATBALLS", RestMenu = restMenus.Single(g => g.Name == "KIDS MENU"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BABY ORGANIC BEEF BURGERS", RestMenu = restMenus.Single(g => g.Name == "KIDS MENU"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "HAPPY CHICKEN LOLLIPOPS", RestMenu = restMenus.Single(g => g.Name == "KIDS MENU"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SECRET SEVEN TOMATO PASTA BAKE", RestMenu = restMenus.Single(g => g.Name == "KIDS MENU"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CHOCOLATE BROWNIE", RestMenu = restMenus.Single(g => g.Name == "KIDS DESSERTS"), Price = 1.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FRUIT", RestMenu = restMenus.Single(g => g.Name == "KIDS DESSERTS"), Price = 1.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "YUMMY ORGANIC ICE LOLLIES", RestMenu = restMenus.Single(g => g.Name == "KIDS DESSERTS"), Price = 1.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ICE CREAM", RestMenu = restMenus.Single(g => g.Name == "KIDS DESSERTS"), Price = 1.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "APEROL SPRITZ", RestMenu = restMenus.Single(g => g.Name == "APRERITIVO"), Price = 6.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BELLINI", RestMenu = restMenus.Single(g => g.Name == "APRERITIVO"), Price = 6.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MEZZO MEZZO", RestMenu = restMenus.Single(g => g.Name == "APRERITIVO"), Price = 6.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "STRAWBERRY ROSSINI", RestMenu = restMenus.Single(g => g.Name == "APRERITIVO"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ELDERFLOWER SPRITZ", RestMenu = restMenus.Single(g => g.Name == "APRERITIVO"), Price = 6.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MORETTI 4.6%", RestMenu = restMenus.Single(g => g.Name == "BEER"), Price = 4.20M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MESSINA 4.7%", RestMenu = restMenus.Single(g => g.Name == "BEER"), Price = 4.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "LIBERTA 5%", RestMenu = restMenus.Single(g => g.Name == "BEER"), Price = 4.30M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GINGER MOJITO", RestMenu = restMenus.Single(g => g.Name == "NON-ALCOHOLIC COCKTAILS"), Price = 3.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "REFRESHER", RestMenu = restMenus.Single(g => g.Name == "NON-ALCOHOLIC COCKTAILS"), Price = 3.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "LYCHEE SPRITZER", RestMenu = restMenus.Single(g => g.Name == "NON-ALCOHOLIC COCKTAILS"), Price = 3.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BERRY BLAST", RestMenu = restMenus.Single(g => g.Name == "NON-ALCOHOLIC COCKTAILS"), Price = 3.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BLACKBERRY MULE", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 6.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "AMALFI COLLINS", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.25M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CAIPIRINHA", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE’S MOJITO", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.25M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "NEGRONI", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SICILIAN DAIQUIRI", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 6.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BLACKBERRY SOUR", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "OUR CLASSIC MARTINI", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GREY GOOSE LE FIZZ", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "AMARETTO SOUR", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 6.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "VANILLA & LEMON MARTINI", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 6.75M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "LA DOLCE VITA", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 6.75M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "LYCHEE & ROSEMARY SOPHIA", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 7.25M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GINGER NUT", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 6.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BRAMBLE", RestMenu = restMenus.Single(g => g.Name == "COCKTAILS"), Price = 6.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GARGANEGA, CANTINA VALPANTENA 12%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 18.55M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SAUVIGNON BLANC DI FRUILI GRAVE, TINTORETTO 12%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 21.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "PINOT GRIGIO, PORTA NOVA 12.5%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 24.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GAVI DI GAVI TERRA ANTICHE, LA GIUSTINIANA 12%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 31.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GRILLO/CHARDONNAY COSTADUNE, MANDRAROSSA 12.5%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 23.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "SOAVE CLASSICO CANTINA DI MONTEFORTE 12.5%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 18.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FALANGHINA, CANTINE ANTONIO CAGGIANO 13%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 37.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "VERDICCHIO DI MATELICA ‘TERRE DI VALBONA’ 12%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 28.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CALVARINO SOAVE CLASSICO, PIEROPAN 12.5%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 33.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "PECORINO, GRAN SASSO ‘ALTA QUOTA’ 13% ABRUZZO", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 36.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "A MANO BIANCO 13%", RestMenu = restMenus.Single(g => g.Name == "WHITE WINE"), Price = 27.75M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MONTEPULCIANO D’ABRUZZO IL FAGGIO 12.5%", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 21.25M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "NERO D’AVOLA, VIGNETI ZABU 13.5% SICILY", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 26.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MORELLINO DI SCANSANO ‘I PERAZZI’, LA MOZZA 13.5% TUSCANY", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 31.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CORVINA, CANTINA VALPANTENA 12% VENETO", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 19.85M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BARBERA, AMONTE, CANTINE VOLPI 12% PIEDMONT", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 21.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "POGGIO TEMPESTA CHIANTI DOCG 13% TUSCANY", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 20.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "PRIMITIVO DI PUGLIA LA MASSERIA 14.5% PUGLIA", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 25.55M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "VALPOLICELLA SUPERIORE RIPASSO ‘REGOLO’, VINCOLA SARTORI 13.5% VENETO", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 35.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TORRIONE, PETROLO 14% TUSCANY", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 36.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "AMARONE DELLA VALPOLICELLA CLASSICO, ALLEGRINI 15.5% VENETO", RestMenu = restMenus.Single(g => g.Name == "RED WINE"), Price = 57.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "PINOT GRIGIO ROSE, PORTA NOVA 12% VENETO", RestMenu = restMenus.Single(g => g.Name == "ROSE WINE"), Price = 24.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "A MANO ROSATA 12% PUGLIA", RestMenu = restMenus.Single(g => g.Name == "ROSE WINE"), Price = 27.75M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "PROSECCO RUSTICO VALDOBBIADENE NINO FRANCO 11%", RestMenu = restMenus.Single(g => g.Name == "SPARKLING"), Price = 34.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE’S ITALIAN PROSECCO NV SPUMANTE 11%", RestMenu = restMenus.Single(g => g.Name == "SPARKLING"), Price = 29.50M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE'S ITALIAN RABOSO ROSATO SPUMANTE 11%", RestMenu = restMenus.Single(g => g.Name == "SPARKLING"), Price = 27.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FRANCIACORTA BELLAVISTA CUVÉE BRUT NV 12% NV", RestMenu = restMenus.Single(g => g.Name == "SPARKLING"), Price = 47.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CHARLES HEIDSIECK BRUT RESERVE NV 12%", RestMenu = restMenus.Single(g => g.Name == "SPARKLING"), Price = 65.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CHARLES HEIDSIECK ROSE RESERVE NV 12%", RestMenu = restMenus.Single(g => g.Name == "SPARKLING"), Price = 73.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BIANCO 12.5%", RestMenu = restMenus.Single(g => g.Name == "JAMIE'S ITALIAN HOUSE WINE"), Price = 23.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ROSSO 12.5%", RestMenu = restMenus.Single(g => g.Name == "JAMIE'S ITALIAN HOUSE WINE"), Price = 23.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ROSATO 12.5%", RestMenu = restMenus.Single(g => g.Name == "JAMIE'S ITALIAN HOUSE WINE"), Price = 23.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BOTTLEGREEN PRESSES", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 3.05M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CAWSTON SPARKLING CLOUDY APPLE", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 2.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FRESH FRUIT JUICES", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 2.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FRUIT JUICE SPRITZ", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 3.00M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MINERAL WATER", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 2.00M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "DIET COKE", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 2.55M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "COKE/ARANCIATA/LIMONATA 330ML", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 2.65M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "HOMEMADE LEMONADE", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 3.05M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "BOTTLEGREEN PRESSES", RestMenu = restMenus.Single(g => g.Name == "SOFT DRINKS"), Price = 3.05M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ESPRESSO MARTINI", RestMenu = restMenus.Single(g => g.Name == "DESSERT COCKTAILS"), Price = 7.50M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TIRAMISU MARTINI", RestMenu = restMenus.Single(g => g.Name == "DESSERT COCKTAILS"), Price = 6.75M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "PASSIONATA", RestMenu = restMenus.Single(g => g.Name == "DESSERT COCKTAILS"), Price = 7.75M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ESPRESSO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.30M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CAFFÈ CORRETTO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 3.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "DOUBLE ESPRESSO/MACCHIATO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.60M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CAFFÈ MAROCCHINO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.65M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "CAPPUCCINO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "JAMIE’S CHOCOLATE ORANGE", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "MACCHIATO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.60M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "LARGE CAPPUCINO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 3.05M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "LATTE", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.95M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "AMERICANO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.35M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "DOUBLE MACCHIATO", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "HOT CHOCOLATE", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.75M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TEA", RestMenu = restMenus.Single(g => g.Name == "HOT DRINKS"), Price = 2.35M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "VIN SANTO TEGRINO", RestMenu = restMenus.Single(g => g.Name == "DIGESTIFS"), Price = 5.35M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "TUACA 35%", RestMenu = restMenus.Single(g => g.Name == "DIGESTIFS"), Price = 3.75M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "ITALIAN LIMONCELLO 29%", RestMenu = restMenus.Single(g => g.Name == "DIGESTIFS"), Price = 2.95M,  RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GRAPPA STAGIONATA 42%", RestMenu = restMenus.Single(g => g.Name == "DIGESTIFS"), Price = 5.65M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "AMARETTO SALIZA 28%", RestMenu = restMenus.Single(g => g.Name == "DIGESTIFS"), Price = 3.45M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "GRAPPA CIVIDINA 40%", RestMenu = restMenus.Single(g => g.Name == "DIGESTIFS"), Price = 3.40M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
                new RestItem { Title = "FOGOLAR BRANDY 38.5%", RestMenu = restMenus.Single(g => g.Name == "DIGESTIFS"), Price = 5.80M, RestItemArtUrl = "/Content/Images/placeholder.gif" },
            }.ForEach(g => context.RestItems.Add(g));
            context.SaveChanges();
        }
    }
}